# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d4aa567c1489ec217089b4b8513e4867df7a3bf000c93cc2cfc449f01a27c40b664fdf772f736a0f74b9efa9d1eb91f0d249b29134d44060bef1e3975cc1e58

test:
  secret_key_base: df96866694e3b7b7fc6098f8956d891854f5ab1a4d29e4a35b849e4513232c76630df85dd3ebf37316db8145918cdc39ad52e7d6bdd5dd25008814003b0124bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
