require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PrincipalGroupesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # PrincipalGroupe. As you add validations to PrincipalGroupe, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PrincipalGroupesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all principal_groupes as @principal_groupes" do
      principal_groupe = PrincipalGroupe.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:principal_groupes)).to eq([principal_groupe])
    end
  end

  describe "GET show" do
    it "assigns the requested principal_groupe as @principal_groupe" do
      principal_groupe = PrincipalGroupe.create! valid_attributes
      get :show, {:id => principal_groupe.to_param}, valid_session
      expect(assigns(:principal_groupe)).to eq(principal_groupe)
    end
  end

  describe "GET new" do
    it "assigns a new principal_groupe as @principal_groupe" do
      get :new, {}, valid_session
      expect(assigns(:principal_groupe)).to be_a_new(PrincipalGroupe)
    end
  end

  describe "GET edit" do
    it "assigns the requested principal_groupe as @principal_groupe" do
      principal_groupe = PrincipalGroupe.create! valid_attributes
      get :edit, {:id => principal_groupe.to_param}, valid_session
      expect(assigns(:principal_groupe)).to eq(principal_groupe)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PrincipalGroupe" do
        expect {
          post :create, {:principal_groupe => valid_attributes}, valid_session
        }.to change(PrincipalGroupe, :count).by(1)
      end

      it "assigns a newly created principal_groupe as @principal_groupe" do
        post :create, {:principal_groupe => valid_attributes}, valid_session
        expect(assigns(:principal_groupe)).to be_a(PrincipalGroupe)
        expect(assigns(:principal_groupe)).to be_persisted
      end

      it "redirects to the created principal_groupe" do
        post :create, {:principal_groupe => valid_attributes}, valid_session
        expect(response).to redirect_to(PrincipalGroupe.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved principal_groupe as @principal_groupe" do
        post :create, {:principal_groupe => invalid_attributes}, valid_session
        expect(assigns(:principal_groupe)).to be_a_new(PrincipalGroupe)
      end

      it "re-renders the 'new' template" do
        post :create, {:principal_groupe => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested principal_groupe" do
        principal_groupe = PrincipalGroupe.create! valid_attributes
        put :update, {:id => principal_groupe.to_param, :principal_groupe => new_attributes}, valid_session
        principal_groupe.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested principal_groupe as @principal_groupe" do
        principal_groupe = PrincipalGroupe.create! valid_attributes
        put :update, {:id => principal_groupe.to_param, :principal_groupe => valid_attributes}, valid_session
        expect(assigns(:principal_groupe)).to eq(principal_groupe)
      end

      it "redirects to the principal_groupe" do
        principal_groupe = PrincipalGroupe.create! valid_attributes
        put :update, {:id => principal_groupe.to_param, :principal_groupe => valid_attributes}, valid_session
        expect(response).to redirect_to(principal_groupe)
      end
    end

    describe "with invalid params" do
      it "assigns the principal_groupe as @principal_groupe" do
        principal_groupe = PrincipalGroupe.create! valid_attributes
        put :update, {:id => principal_groupe.to_param, :principal_groupe => invalid_attributes}, valid_session
        expect(assigns(:principal_groupe)).to eq(principal_groupe)
      end

      it "re-renders the 'edit' template" do
        principal_groupe = PrincipalGroupe.create! valid_attributes
        put :update, {:id => principal_groupe.to_param, :principal_groupe => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested principal_groupe" do
      principal_groupe = PrincipalGroupe.create! valid_attributes
      expect {
        delete :destroy, {:id => principal_groupe.to_param}, valid_session
      }.to change(PrincipalGroupe, :count).by(-1)
    end

    it "redirects to the principal_groupes list" do
      principal_groupe = PrincipalGroupe.create! valid_attributes
      delete :destroy, {:id => principal_groupe.to_param}, valid_session
      expect(response).to redirect_to(principal_groupes_url)
    end
  end

end
