require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SousGroupesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # SousGroupe. As you add validations to SousGroupe, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SousGroupesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all sous_groupes as @sous_groupes" do
      sous_groupe = SousGroupe.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:sous_groupes)).to eq([sous_groupe])
    end
  end

  describe "GET show" do
    it "assigns the requested sous_groupe as @sous_groupe" do
      sous_groupe = SousGroupe.create! valid_attributes
      get :show, {:id => sous_groupe.to_param}, valid_session
      expect(assigns(:sous_groupe)).to eq(sous_groupe)
    end
  end

  describe "GET new" do
    it "assigns a new sous_groupe as @sous_groupe" do
      get :new, {}, valid_session
      expect(assigns(:sous_groupe)).to be_a_new(SousGroupe)
    end
  end

  describe "GET edit" do
    it "assigns the requested sous_groupe as @sous_groupe" do
      sous_groupe = SousGroupe.create! valid_attributes
      get :edit, {:id => sous_groupe.to_param}, valid_session
      expect(assigns(:sous_groupe)).to eq(sous_groupe)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SousGroupe" do
        expect {
          post :create, {:sous_groupe => valid_attributes}, valid_session
        }.to change(SousGroupe, :count).by(1)
      end

      it "assigns a newly created sous_groupe as @sous_groupe" do
        post :create, {:sous_groupe => valid_attributes}, valid_session
        expect(assigns(:sous_groupe)).to be_a(SousGroupe)
        expect(assigns(:sous_groupe)).to be_persisted
      end

      it "redirects to the created sous_groupe" do
        post :create, {:sous_groupe => valid_attributes}, valid_session
        expect(response).to redirect_to(SousGroupe.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sous_groupe as @sous_groupe" do
        post :create, {:sous_groupe => invalid_attributes}, valid_session
        expect(assigns(:sous_groupe)).to be_a_new(SousGroupe)
      end

      it "re-renders the 'new' template" do
        post :create, {:sous_groupe => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested sous_groupe" do
        sous_groupe = SousGroupe.create! valid_attributes
        put :update, {:id => sous_groupe.to_param, :sous_groupe => new_attributes}, valid_session
        sous_groupe.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested sous_groupe as @sous_groupe" do
        sous_groupe = SousGroupe.create! valid_attributes
        put :update, {:id => sous_groupe.to_param, :sous_groupe => valid_attributes}, valid_session
        expect(assigns(:sous_groupe)).to eq(sous_groupe)
      end

      it "redirects to the sous_groupe" do
        sous_groupe = SousGroupe.create! valid_attributes
        put :update, {:id => sous_groupe.to_param, :sous_groupe => valid_attributes}, valid_session
        expect(response).to redirect_to(sous_groupe)
      end
    end

    describe "with invalid params" do
      it "assigns the sous_groupe as @sous_groupe" do
        sous_groupe = SousGroupe.create! valid_attributes
        put :update, {:id => sous_groupe.to_param, :sous_groupe => invalid_attributes}, valid_session
        expect(assigns(:sous_groupe)).to eq(sous_groupe)
      end

      it "re-renders the 'edit' template" do
        sous_groupe = SousGroupe.create! valid_attributes
        put :update, {:id => sous_groupe.to_param, :sous_groupe => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sous_groupe" do
      sous_groupe = SousGroupe.create! valid_attributes
      expect {
        delete :destroy, {:id => sous_groupe.to_param}, valid_session
      }.to change(SousGroupe, :count).by(-1)
    end

    it "redirects to the sous_groupes list" do
      sous_groupe = SousGroupe.create! valid_attributes
      delete :destroy, {:id => sous_groupe.to_param}, valid_session
      expect(response).to redirect_to(sous_groupes_url)
    end
  end

end
